<?php

namespace Aym3ntn\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function findByUser($user, $type){
        $query = $this->createQueryBuilder('n')
            ->where('n.type = :type')
            ->setParameter('type', $type)
            ->join('n.targets','t','WITH','t.id = :id')
            ->andWhere('t.id != :id')
            ->setParameter('id', $user);
        return $query->getQuery()->getResult();
    }

}
